stages:
  download_weather:
    cmd: mkdir -p data/raw/weather_tx_asos && cd data/raw/weather_tx_asos && 
      ../../../.venv/bin/python ../../../scripts/download_asos_weather.py 
      --execute
    deps:
    - scripts/download_asos_weather.py
    outs:
    - data/raw/weather_tx_asos
  extract_ercot_backcast:
    cmd: cd data/interim/ercot_backcast && ../../../.venv/bin/python 
      ../../../scripts/extract_ercot_backcast.py
    deps:
    - data/raw/ercot_backcast
    - scripts/extract_ercot_backcast.py
    outs:
    - data/interim/ercot_backcast
  extract_ercot_map:
    cmd: cd data/interim/ercot_map && ../../../.venv/bin/python ../../../scripts/extract_ercot_map.py
    deps:
    - data/raw/ercot_map/eGRID2023_Subregions.shp
    - data/raw/ercot_map/eGRID2023_Subregions.shx
    - data/raw/ercot_map/eGRID2023_Subregions.dbf
    - data/raw/ercot_map/eGRID2023_Subregions.prj
    - scripts/extract_ercot_map.py
    outs:
    - data/interim/ercot_map/ercot_boundary.geojson
